# Generated by Django 4.2.17 on 2026-01-11 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('recipients', models.TextField(blank=True, help_text='Un email par ligne')),
                ('send_hour', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('send_minute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
            ],
            options={
                'verbose_name': 'Configuration Email',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('a', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('b', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('c', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('d', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('e', models.DecimalField(decimal_places=4, default=2, help_text='Ne peut pas être 0', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('N1', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('N2', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('N3', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('N4', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compute_config_hash', models.CharField(blank=True, editable=False, max_length=64)),
            ],
            options={
                'db_table': 'scenarios',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.scenario')),
            ],
            options={
                'db_table': 'scenario_symbols',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('exchange', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenarios', models.ManyToManyField(related_name='symbols', through='core.ScenarioSymbol', to='core.scenario')),
            ],
            options={
                'db_table': 'symbols',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='scenariosymbol',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol'),
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'job_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'job_name'], name='job_logs_created_1756e4_idx'), models.Index(fields=['level'], name='job_logs_level_f50b64_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('P', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('M', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('X', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('M1', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('X1', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('T', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('Q', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('S', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('K1', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('K2', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('K3', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('K4', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('V', models.DecimalField(blank=True, decimal_places=4, help_text='Variation % jour', max_digits=10, null=True)),
                ('slope_P', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ratio_P', models.DecimalField(blank=True, decimal_places=4, help_text='En %', max_digits=10, null=True)),
                ('amp_h', models.DecimalField(blank=True, decimal_places=4, help_text='En %', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.scenario')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.symbol')),
            ],
            options={
                'db_table': 'daily_metrics',
                'ordering': ['symbol', 'scenario', '-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='core.symbol')),
            ],
            options={
                'db_table': 'daily_bars',
                'ordering': ['symbol', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('alert_codes', models.CharField(help_text='Ex: A1,E1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.scenario')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.symbol')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-date', 'symbol'],
            },
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['code', 'exchange'], name='symbols_code_5d61fe_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['is_active'], name='symbols_is_acti_ec41bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenariosymbol',
            unique_together={('scenario', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['symbol', 'scenario', 'date'], name='daily_metri_symbol__4c2c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['date'], name='daily_metri_date_07dd2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymetric',
            unique_together={('symbol', 'scenario', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailybar',
            index=models.Index(fields=['symbol', 'date'], name='daily_bars_symbol__47cf34_idx'),
        ),
        migrations.AddIndex(
            model_name='dailybar',
            index=models.Index(fields=['date'], name='daily_bars_date_865d57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailybar',
            unique_together={('symbol', 'date')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['date', 'scenario'], name='alerts_date_b339ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('symbol', 'scenario', 'date')},
        ),
    ]
