# Generated by Django 4.2.17 on 2026-01-11 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stratégies de backtest',
                'db_table': 'backtest_strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('CP', models.DecimalField(decimal_places=2, default=0, help_text='Capital total (0 = infini)', max_digits=15)),
                ('CT', models.DecimalField(decimal_places=2, help_text='Capital par ticker', max_digits=15)),
                ('X', models.DecimalField(decimal_places=2, help_text='Seuil ratio_P (en %)', max_digits=5)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Créé'), ('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='CREATED', max_length=10)),
                ('total_BT', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_BMJ', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('nb_jours_ouvres', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='core.scenario')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to='backtesting.backteststrategy')),
            ],
            options={
                'db_table': 'backtest_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('N', models.IntegerField(default=0, help_text='Nombre de coups')),
                ('G', models.DecimalField(blank=True, decimal_places=4, help_text='Gain dernier coup %', max_digits=10, null=True)),
                ('S_G_N', models.DecimalField(blank=True, decimal_places=4, help_text='Moyenne gains %', max_digits=10, null=True)),
                ('BT', models.DecimalField(blank=True, decimal_places=4, help_text='Bénéfice total', max_digits=15, null=True)),
                ('BMJ', models.DecimalField(blank=True, decimal_places=4, help_text='Bénéfice moyen/jour', max_digits=15, null=True)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position_qty', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='backtesting.backtestrun')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'backtest_daily_stats',
                'ordering': ['run', 'symbol', 'date'],
            },
        ),
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Acheter'), ('SELL', 'Vendre')], max_length=4)),
                ('signal', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('D1', 'D1'), ('E1', 'E1'), ('F1', 'F1'), ('G1', 'G1'), ('H1', 'H1')], max_length=2)),
                ('position_size_pct', models.DecimalField(decimal_places=2, default=100, help_text='% du cash à investir (100 = tout)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='backtesting.backteststrategy')),
            ],
            options={
                'db_table': 'strategy_rules',
                'ordering': ['strategy', 'action'],
                'unique_together': {('strategy', 'action', 'signal')},
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField(help_text='Date du signal')),
                ('execution_date', models.DateField(help_text="Date d'exécution (J+1)")),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('signal', models.CharField(max_length=2)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cash_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gain_pct', models.DecimalField(blank=True, decimal_places=4, help_text='G en %', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='backtesting.backtestrun')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'backtest_trades',
                'ordering': ['run', 'execution_date', 'symbol'],
                'indexes': [models.Index(fields=['run', 'symbol', 'execution_date'], name='backtest_tr_run_id_567bed_idx'), models.Index(fields=['run', 'execution_date'], name='backtest_tr_run_id_4db459_idx')],
            },
        ),
        migrations.CreateModel(
            name='BacktestRunSymbolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CT_override', models.DecimalField(decimal_places=2, max_digits=15)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_settings', to='backtesting.backtestrun')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.symbol')),
            ],
            options={
                'db_table': 'backtest_run_symbol_settings',
                'unique_together': {('run', 'symbol')},
            },
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['-created_at'], name='backtest_ru_created_764ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['scenario', 'strategy'], name='backtest_ru_scenari_6eb6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestrun',
            index=models.Index(fields=['status'], name='backtest_ru_status_48238d_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestdailystat',
            index=models.Index(fields=['run', 'date'], name='backtest_da_run_id_c6eafd_idx'),
        ),
        migrations.AddIndex(
            model_name='backtestdailystat',
            index=models.Index(fields=['run', 'symbol', 'date'], name='backtest_da_run_id_cad748_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='backtestdailystat',
            unique_together={('run', 'symbol', 'date')},
        ),
    ]
